import fs from "node:fs";
import path from "node:path";

import { UNSTYLED_DIRS } from "./component-dirs.mjs";

/**
 * The stylesheet entries behind `ropav/styles/core`, `ropav/styles/components` and
 * `ropav/styles/<name>`, written into `dist/styles/` by `build.mjs`.
 *
 * `ropav/styles` is everything at once. These are the same rules cut so an app can take the core
 * and the components it renders with its first paint, and every other component later — when the
 * code that draws them is split off and loaded on demand. A component's entry carries the files of
 * everything it renders as well as its own, which is the part an app cannot be expected to know: a
 * `Modal` draws a `CloseButton`, a `ListBox` draws `VirtualizerItem`s.
 *
 * No component entry carries the core. One loaded late would bring the default theme back after
 * the app's own `@layer theme` tokens, and the later of two declarations in one layer wins.
 */

/** The layer order. Each entry restates it, so whichever stylesheet a page meets first sets it. */
const LAYER_ORDER = "@layer theme, base, components, utilities;";

const GENERATED = "/* Generated by scripts/style-entries.mjs — edit that, not this. */";

/** `import X from "../dir/…"`, `import { A, b } from "@/components/dir"`, and the two together. */
const COMPONENT_IMPORT =
  /^import\s+(?!type\s)([^;]*?)\s+from\s+"(?:\.\.\/|@\/components\/)([a-z][a-z0-9-]*)(?:\/[^"]*)?"/gm;

/** `import { buttonVariants, … } from "@ropav/styles"`. */
const VARIANTS_IMPORT = /^import\s+\{([^}]*)\}\s+from\s+"@ropav\/styles"/gm;

/** A component, as opposed to a context hook, a helper or a constant: `CloseButton`, not `useX`. */
const COMPONENT_NAME = /^[A-Z][a-z]/;

/**
 * The bindings an import clause makes, `type` specifiers and `X as` left out.
 *
 * @param {string} clause
 * @returns {string[]}
 */
const bindings = (clause) =>
  clause
    .replace(/[{}]/g, ",")
    .split(",")
    .map((specifier) => specifier.trim())
    .filter((specifier) => specifier && !specifier.startsWith("type "))
    .map((specifier) => specifier.split(/\s+as\s+/).at(-1) ?? specifier);

/**
 * `listboxItemVariants` → `listboxitem`, for matching a helper to the directory that owns it.
 *
 * @param {string} name
 */
const squash = (name) =>
  name
    .replace(/Variants$/, "")
    .replaceAll("-", "")
    .toLowerCase();

/**
 * What each component directory renders of the others: a component it imports by name, or the
 * class names of another's `…Variants` helper. Context hooks and types are not rendering, and
 * neither is a story — the graph is what the published code draws.
 *
 * @param {string} componentsDir `src/components`.
 * @returns {Map<string, string[]>} Each directory, and the directories it renders directly.
 */
export function readRenderGraph(componentsDir) {
  const dirs = fs
    .readdirSync(componentsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
  const owners = new Map(dirs.map((dir) => [squash(dir), dir]));

  /** @type {Map<string, string[]>} */
  const graph = new Map();

  for (const dir of dirs) {
    const renders = new Set();

    for (const file of fs.readdirSync(path.join(componentsDir, dir))) {
      if (!/\.(ts|vue)$/.test(file) || /\.(stories|test)\.ts$/.test(file)) continue;

      const source = fs.readFileSync(path.join(componentsDir, dir, file), "utf8");

      for (const [, clause = "", target = ""] of source.matchAll(COMPONENT_IMPORT)) {
        if (bindings(clause).some((name) => COMPONENT_NAME.test(name))) renders.add(target);
      }

      for (const [, clause = ""] of source.matchAll(VARIANTS_IMPORT)) {
        for (const name of bindings(clause)) {
          const owner = name.endsWith("Variants") ? owners.get(squash(name)) : undefined;

          if (owner) renders.add(owner);
        }
      }
    }

    renders.delete(dir);
    graph.set(dir, [...renders].sort());
  }

  return graph;
}

/**
 * The component files in the order `@ropav/styles/components/index.css` imports them, which is
 * the order every entry lists them in.
 *
 * @param {string} indexCss The text of that file.
 * @returns {string[]}
 */
export const readComponentOrder = (indexCss) =>
  [...indexCss.matchAll(/^@import "\.\/([a-z0-9-]+)\.css";/gm)].map(([, name]) => name ?? "");

/**
 * The entries, as file name → stylesheet text.
 *
 * Pure, so a test can read what the build would write without a build.
 *
 * @param {object} options
 * @param {string[]} options.components The directories with a subpath of their own.
 * @param {Map<string, string[]>} options.graph From `readRenderGraph`.
 * @param {string[]} options.order From `readComponentOrder`.
 * @returns {Record<string, string>}
 */
export function buildStyleEntries({ components, graph, order }) {
  const styled = new Set(order);

  for (const dir of graph.keys()) {
    if (!styled.has(dir) && !UNSTYLED_DIRS.has(dir)) {
      throw new Error(
        `${dir} has no file in @ropav/styles/components and is not listed as unstyled`,
      );
    }
  }

  /**
   * The directory and everything it renders, through unstyled hosts like `overlay` too.
   *
   * @param {string} dir
   */
  const closure = (dir) => {
    const seen = new Set();
    const stack = [dir];

    while (stack.length > 0) {
      const next = /** @type {string} */ (stack.pop());

      if (seen.has(next)) continue;
      seen.add(next);
      stack.push(...(graph.get(next) ?? []));
    }

    return order.filter((name) => seen.has(name));
  };

  /** @type {Record<string, string>} */
  const entries = {
    "components.css": [
      GENERATED,
      '@import "@ropav/styles/components.css";',
      '@import "../styles-overrides.css";',
      "",
    ].join("\n"),
    "core.css": [GENERATED, '@import "@ropav/styles/core.css";', ""].join("\n"),
  };

  for (const name of components) {
    if (UNSTYLED_DIRS.has(name)) continue;

    const files = closure(name);
    const lines = [
      GENERATED,
      LAYER_ORDER,
      ...files.map((file) => `@import "@ropav/styles/components/${file}.css" layer(components);`),
    ];

    // `styles-overrides.css` holds `button-group` rules only, so it travels with that file.
    if (files.includes("button-group")) lines.push('@import "../styles-overrides.css";');

    entries[`${name}.css`] = `${lines.join("\n")}\n`;
  }

  return entries;
}
