packages:
  - "packages/**/**"

catalog:
  "@tailwindcss/cli": 4.3.3
  "@tailwindcss/postcss": 4.3.3
  "@tailwindcss/vite": 4.3.3
  "@types/node": 24.13.3
  "@vitejs/plugin-vue": 6.0.8
  "@vitest/browser": 5.0.0
  "@vitest/browser-playwright": 5.0.0
  "@vue/compiler-vapor": 3.6.0-rc.7
  tailwindcss: 4.3.3
  typescript: npm:typescript-native-bridge@6.0.3-bridge.16.tsgo.7.0.2
  vite: 8.2.2
  vitest: 5.0.0
  vue: 3.6.0-rc.7
  vue-tsc: 3.3.11

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "core-js"
  - "esbuild"
  - "lmdb"
  - "msgpackr-extract"
  - "protobufjs"
  - "sharp"
  - "unrs-resolver"
