import { DropdownMenuItem as DropdownMenuItemPrimitive } from './dropdown-menu-primitives';
import type { DropdownMenuItem as DropdownMenuDataItem } from './types';

export { default as DropdownMenu } from './dropdown-menu.vue';
export {
    DropdownMenuCheckboxItem,
    DropdownMenuContent,
    DropdownMenuContextTrigger,
    DropdownMenuItemIndicator,
    DropdownMenuLabel,
    DropdownMenuPortal,
    DropdownMenuRadioGroup,
    DropdownMenuRadioItem,
    DropdownMenuRoot,
    DropdownMenuSeparator,
    DropdownMenuSub,
    DropdownMenuSubContent,
    DropdownMenuSubTrigger,
    DropdownMenuTrigger,
} from './dropdown-menu-primitives';
export const DropdownMenuItem = DropdownMenuItemPrimitive;
export type DropdownMenuItem = DropdownMenuDataItem;
export { useDropdownMenu } from './useDropdownMenu';
export type {
    DropdownMenuAs,
    DropdownMenuCheckedState,
    DropdownMenuCheckboxItemPrimitiveProps,
    DropdownMenuCloseOptions,
    DropdownMenuContentPrimitiveProps,
    DropdownMenuContentProps,
    DropdownMenuContextTriggerPrimitiveProps,
    DropdownMenuFocusTarget,
    DropdownMenuInteractOutsideDetail,
    DropdownMenuInteractOutsideEvent,
    DropdownMenuItemIndicatorPrimitiveProps,
    DropdownMenuItemPath,
    DropdownMenuItemPrimitiveProps,
    DropdownMenuItemPrimitiveSlotProps,
    DropdownMenuItemProps,
    DropdownMenuItemSlotProps,
    DropdownMenuItemValue,
    DropdownMenuLabelPrimitiveProps,
    DropdownMenuOffset,
    DropdownMenuOffsetOptions,
    DropdownMenuOpenOptions,
    DropdownMenuPlacement,
    DropdownMenuPoint,
    DropdownMenuPortalPrimitiveProps,
    DropdownMenuProps,
    DropdownMenuRadioGroupPrimitiveProps,
    DropdownMenuRadioItemPrimitiveProps,
    DropdownMenuRenderedItem,
    DropdownMenuRootPrimitiveProps,
    DropdownMenuRootSlotProps,
    DropdownMenuSelectDetail,
    DropdownMenuSelectEvent,
    DropdownMenuSeparatorPrimitiveProps,
    DropdownMenuSlotProps,
    DropdownMenuSubContentPrimitiveProps,
    DropdownMenuSubPrimitiveProps,
    DropdownMenuSubmenuProps,
    DropdownMenuSubTriggerPrimitiveProps,
    DropdownMenuTriggerPrimitiveProps,
    DropdownMenuTriggerProps,
    DropdownMenuVirtualAnchor,
} from './types';
