import StyleDictionary from 'style-dictionary';
import { getReferences, usesReferences } from 'style-dictionary/utils';
import {
    cssCustomProperty,
    hasCssCustomProperty,
    hasScssVariable,
    scssName,
    tokenPath,
} from './token-output-policy.mjs';
import { getDerivedColorVariables } from './color-system.mjs';

const fileHeaderLines = [
    '// This file is generated by Style Dictionary.',
    '// Do not edit directly; update tokens/**/*.tokens.json instead.',
    '',
];

const sectionByTokenPath = {
    'font.family': 'Font family',
    color: 'Colors',
    'font.size': 'Font sizes',
    'font.weight': 'Font weights',
    heading: 'Headings',
    'line-height': 'Line heights',
    spacing: 'Spacing',
    radius: 'Border radius',
    'border.width': 'Border widths',
    size: 'Control sizes',
    component: 'Component tokens',
    'z-index': 'Z-index',
    opacity: 'Opacity',
    shadow: 'Shadows',
    transition: 'Transitions',
};

const sectionOrder = [...new Set(Object.values(sectionByTokenPath))];

const defaultDictionary = await createStyleDictionary({
    source: ['tokens/default/**/*.tokens.json'],
    platforms: {},
});
const darkOverrideDictionary = await createStyleDictionary({
    source: ['tokens/dark/**/*.tokens.json'],
    platforms: {},
});
const darkDictionary = await createStyleDictionary({
    include: ['tokens/default/**/*.tokens.json'],
    source: ['tokens/dark/**/*.tokens.json'],
    platforms: {},
});

// Keep dark override file order, while using merged metadata from include + source.
const darkOverrideTokens = darkOverrideDictionary.allTokens.map(({ key }) => {
    const defaultToken = defaultDictionary.tokenMap.get(key);
    if (!defaultToken) {
        throw new Error(
            `Dark override token has no default token: ${tokenPath({ key }).join('.')}`,
        );
    }

    const mergedToken = darkDictionary.tokenMap.get(key);
    if (!mergedToken) {
        throw new Error(`Missing token at ${tokenPath({ key }).join('.')}`);
    }

    return mergedToken;
});

export default {
    usesDtcg: true,
    source: ['tokens/default/**/*.tokens.json'],
    hooks: {
        formats: {
            'ropav/variables-scss': ({ dictionary }) => renderVariablesScss(dictionary),
            'ropav/tokens-scss': ({ dictionary }) => renderTokensScss(dictionary),
        },
    },
    platforms: {
        scss: {
            buildPath: 'src/styles/',
            files: [
                {
                    destination: '_variables.scss',
                    format: 'ropav/variables-scss',
                },
                {
                    destination: '_tokens.scss',
                    format: 'ropav/tokens-scss',
                },
            ],
        },
    },
};

async function createStyleDictionary(config) {
    const dictionary = new StyleDictionary({
        log: {
            verbosity: 'silent',
        },
        ...config,
        usesDtcg: true,
    });
    await dictionary.hasInitialized;

    return dictionary;
}

function renderVariablesScss(dictionary) {
    const lines = [...fileHeaderLines];

    for (const section of sectionOrder) {
        const tokens = dictionary.allTokens.filter(
            (token) => tokenSection(token) === section && hasScssVariable(token),
        );
        if (tokens.length === 0) continue;

        lines.push(`// ${section}`);
        const maxNameLength = Math.max(...tokens.map((token) => scssName(token).length));
        for (const token of tokens) {
            lines.push(
                `$${scssName(token).padEnd(maxNameLength)}: ${valueToSassValue(tokenValue(token), dictionary)} !default;`,
            );
        }
        lines.push('');
    }

    return `${lines.join('\n').trimEnd()}\n`;
}

function renderTokensScss(dictionary) {
    const lines = [
        ...fileHeaderLines,
        "@use 'variables' as *;",
        '',
        '@layer ropav.tokens, ropav.components;',
        '',
        '@layer ropav.tokens {',
        ':root {',
    ];

    for (const section of sectionOrder) {
        const tokens = dictionary.allTokens.filter(
            (token) => tokenSection(token) === section && hasCssCustomProperty(token),
        );
        if (tokens.length === 0) continue;

        lines.push(`    // ${section}`);
        pushCssDeclarations(lines, tokens, dictionary);
        if (section === 'Colors') {
            lines.push('');
            lines.push('    // Derived colors');
            pushCssVariableDeclarations(lines, getDerivedColorVariables('light'));
        }
        lines.push('');
    }

    lines.push('}', '');
    lines.push('html.dark,');
    lines.push('[data-rp-color-scheme="dark"] {');
    lines.push('    // Derived colors');
    pushCssVariableDeclarations(lines, getDerivedColorVariables('dark'));
    lines.push('');

    for (const section of sectionOrder) {
        const tokens = darkOverrideTokens.filter(
            (token) => tokenSection(token) === section && hasCssCustomProperty(token),
        );
        if (tokens.length === 0) continue;

        lines.push(`    // ${section}`);
        pushCssDeclarations(lines, tokens, dictionary, { forceRawValue: true });
        lines.push('');
    }

    lines.push('}', '');
    lines.push('}', '');
    return lines.join('\n');
}

function pushCssDeclarations(lines, tokens, dictionary, options = {}) {
    const maxNameLength = Math.max(...tokens.map((token) => cssCustomProperty(token).length));
    for (const token of tokens) {
        const name = cssCustomProperty(token).padEnd(maxNameLength);
        const value =
            options.forceRawValue || !hasScssVariable(token)
                ? valueToCustomPropertyValue(tokenValue(token), dictionary)
                : `#{$${scssName(token)}}`;
        lines.push(`    ${name}: ${value};`);
    }
}

function pushCssVariableDeclarations(lines, variables) {
    const entries = Object.entries(variables);
    const maxNameLength = Math.max(...entries.map(([name]) => name.length));
    for (const [name, value] of entries) {
        lines.push(`    ${name.padEnd(maxNameLength)}: ${value};`);
    }
}

function tokenValue(token) {
    return token.original?.$value ?? token.$value;
}

function valueToSassValue(value, dictionary) {
    return valueToScssValue(value, dictionary, { exactReferenceAsVariable: true });
}

function valueToCustomPropertyValue(value, dictionary) {
    return valueToScssValue(value, dictionary, { referenceAsCustomProperty: true });
}

function valueToScssValue(value, dictionary, options = {}) {
    if (typeof value === 'number') return String(value);
    if (typeof value !== 'string') {
        throw new TypeError(`Unsupported token value: ${JSON.stringify(value)}`);
    }

    const references = tokenReferences(value, dictionary);
    const [reference] = references;
    if (options.referenceAsCustomProperty) {
        return replaceReferences(value, references, (referencedToken) =>
            hasCssCustomProperty(referencedToken)
                ? `var(${cssCustomProperty(referencedToken)})`
                : referenceToSassValue(referencedToken, dictionary),
        );
    }

    if (
        options.exactReferenceAsVariable &&
        references.length === 1 &&
        isExactReference(value, reference)
    ) {
        return hasScssVariable(reference)
            ? `$${scssName(reference)}`
            : valueToScssValue(tokenValue(reference), dictionary);
    }

    return replaceReferences(value, references, (referencedToken) =>
        referenceToSassValue(referencedToken, dictionary),
    );
}

function referenceToSassValue(reference, dictionary) {
    if (hasScssVariable(reference)) return `#{$${scssName(reference)}}`;

    return valueToScssValue(tokenValue(reference), dictionary, { referenceAsCustomProperty: true });
}

function tokenReferences(value, dictionary) {
    if (!usesReferences(value)) return [];

    return getReferences(value, dictionary.tokens, {
        usesDtcg: true,
        unfilteredTokens: dictionary.unfilteredTokens,
    });
}

function isExactReference(value, reference) {
    return new RegExp(`^\\{${escapeRegExp(reference.ref.join('.'))}(?:\\.\\$?value)?\\}$`).test(
        value,
    );
}

function replaceReferences(value, references, getReplacement) {
    let result = value;

    for (const reference of references) {
        const referencePattern = new RegExp(
            `\\{${escapeRegExp(reference.ref.join('.'))}(?:\\.\\$?value)?\\}`,
            'g',
        );
        result = result.replace(referencePattern, getReplacement(reference));
    }

    return result;
}

function escapeRegExp(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function tokenSection(token) {
    const [category, type] = tokenPath(token);
    const section = sectionByTokenPath[`${category}.${type}`] ?? sectionByTokenPath[category];

    if (section) return section;

    throw new Error(`No output section configured for ${tokenPath(token).join('.')}`);
}
