import { describe, expect, it } from 'vitest';
import {
    accordionItemParts,
    accordionParts,
    alertParts,
    aspectRatioParts,
    avatarParts,
    badgeParts,
    buttonGroupParts,
    buttonLinkParts,
    buttonParts,
    calendarParts,
    cardParts,
    checkboxParts,
    collapseParts,
    colorInputParts,
    colorPickerParts,
    colorSwatchParts,
    comboboxParts,
    dropdownMenuParts,
    dropzoneParts,
    fieldParts,
    fileInputParts,
    focusTrapParts,
    hoverCardParts,
    iconButtonParts,
    inputParts,
    modalParts,
    multiSelectParts,
    numberInputParts,
    overlayParts,
    paginationParts,
    popoverParts,
    progressParts,
    radioGroupParts,
    radioParts,
    rangeSliderParts,
    scrollAreaParts,
    segmentedControlParts,
    selectParts,
    sliderParts,
    switchParts,
    tagsInputParts,
    tabsContentParts,
    tabsListParts,
    tabsParts,
    tabsTriggerParts,
    textareaParts,
    toastParts,
    toastViewportParts,
    tooltipParts,
} from './index';

describe('public semantic part catalog', () => {
    it('contains only the documented semantic parts', () => {
        expect({
            Accordion: accordionParts,
            AccordionItem: accordionItemParts,
            Alert: alertParts,
            AspectRatio: aspectRatioParts,
            Avatar: avatarParts,
            Badge: badgeParts,
            Button: buttonParts,
            ButtonGroup: buttonGroupParts,
            ButtonLink: buttonLinkParts,
            Calendar: calendarParts,
            Card: cardParts,
            Checkbox: checkboxParts,
            Collapse: collapseParts,
            ColorInput: colorInputParts,
            ColorPicker: colorPickerParts,
            ColorSwatch: colorSwatchParts,
            Combobox: comboboxParts,
            DropdownMenu: dropdownMenuParts,
            Dropzone: dropzoneParts,
            Field: fieldParts,
            FileInput: fileInputParts,
            FocusTrap: focusTrapParts,
            HoverCard: hoverCardParts,
            IconButton: iconButtonParts,
            Input: inputParts,
            Modal: modalParts,
            MultiSelect: multiSelectParts,
            NumberInput: numberInputParts,
            Overlay: overlayParts,
            Pagination: paginationParts,
            Popover: popoverParts,
            Progress: progressParts,
            Radio: radioParts,
            RadioGroup: radioGroupParts,
            RangeSlider: rangeSliderParts,
            ScrollArea: scrollAreaParts,
            SegmentedControl: segmentedControlParts,
            Select: selectParts,
            Slider: sliderParts,
            Switch: switchParts,
            TagsInput: tagsInputParts,
            Tabs: tabsParts,
            TabsContent: tabsContentParts,
            TabsList: tabsListParts,
            TabsTrigger: tabsTriggerParts,
            Textarea: textareaParts,
            Toast: toastParts,
            ToastViewport: toastViewportParts,
            Tooltip: tooltipParts,
        }).toEqual({
            Accordion: ['root'],
            AccordionItem: ['root', 'trigger', 'title', 'icon', 'content'],
            Alert: ['root', 'icon', 'title', 'description', 'body', 'action', 'close'],
            AspectRatio: ['root'],
            Avatar: ['root', 'image', 'fallback'],
            Badge: ['root', 'left', 'label', 'right'],
            Button: ['root', 'loader', 'left', 'label', 'right'],
            ButtonGroup: ['root'],
            ButtonLink: ['root', 'loader', 'left', 'label', 'right'],
            Calendar: [
                'root',
                'header',
                'previousControl',
                'monthLabel',
                'nextControl',
                'weekdays',
                'weekday',
                'grid',
                'week',
                'dayCell',
                'day',
            ],
            Card: ['root', 'header', 'title', 'description', 'body', 'footer'],
            Checkbox: ['root', 'input', 'indicator', 'label'],
            Collapse: ['root', 'trigger', 'content'],
            ColorInput: [
                'root',
                'control',
                'input',
                'preview',
                'eyeDropper',
                'content',
                'picker',
                'pickerControl',
                'pickerHandle',
                'pickerSwatches',
                'pickerSwatch',
            ],
            ColorPicker: ['root', 'label', 'control', 'handle', 'swatches', 'swatch'],
            ColorSwatch: ['root'],
            Combobox: [
                'root',
                'input',
                'indicator',
                'clear',
                'toggle',
                'content',
                'option',
                'empty',
            ],
            DropdownMenu: [
                'root',
                'trigger',
                'content',
                'item',
                'label',
                'shortcut',
                'submenu',
                'submenuIndicator',
                'empty',
            ],
            Dropzone: ['root', 'input', 'content', 'label', 'description'],
            Field: ['root', 'label', 'required', 'control', 'description'],
            FileInput: ['root', 'input', 'trigger', 'value'],
            FocusTrap: ['root'],
            HoverCard: ['root', 'trigger', 'content'],
            IconButton: ['root', 'loader', 'icon'],
            Input: ['root', 'input', 'left', 'right'],
            Modal: [
                'root',
                'overlay',
                'panel',
                'header',
                'title',
                'description',
                'body',
                'footer',
                'close',
            ],
            MultiSelect: [
                'root',
                'pills',
                'pill',
                'pillLabel',
                'pillRemove',
                'input',
                'indicator',
                'clear',
                'toggle',
                'content',
                'option',
                'empty',
            ],
            NumberInput: ['root', 'input', 'control'],
            Overlay: ['root'],
            Pagination: ['root', 'items', 'control', 'page', 'ellipsis'],
            Popover: ['root', 'trigger', 'content'],
            Progress: ['root', 'label', 'value', 'track', 'indicator'],
            Radio: ['root', 'input', 'indicator', 'label'],
            RadioGroup: ['root'],
            RangeSlider: [
                'root',
                'label',
                'value',
                'track',
                'range',
                'input',
                'thumb',
                'mark',
                'markLabel',
                'tooltip',
            ],
            ScrollArea: ['root', 'viewport', 'content', 'scrollbar', 'thumb', 'corner'],
            SegmentedControl: ['root', 'control', 'input', 'indicator', 'label'],
            Select: [
                'root',
                'trigger',
                'value',
                'indicator',
                'clear',
                'content',
                'option',
                'empty',
            ],
            Slider: [
                'root',
                'label',
                'value',
                'track',
                'range',
                'input',
                'thumb',
                'mark',
                'markLabel',
                'tooltip',
            ],
            Switch: ['root', 'input', 'track', 'thumb', 'label'],
            TagsInput: ['root', 'tags', 'tag', 'tagLabel', 'tagRemove', 'input', 'clear'],
            Tabs: ['root'],
            TabsContent: ['root'],
            TabsList: ['root'],
            TabsTrigger: ['root'],
            Textarea: ['root', 'input'],
            Toast: ['root', 'icon', 'title', 'description', 'body', 'action', 'close'],
            ToastViewport: [
                'root',
                'item',
                'toast',
                'toastIcon',
                'toastTitle',
                'toastDescription',
                'toastBody',
                'toastAction',
                'toastClose',
            ],
            Tooltip: ['root', 'trigger', 'content'],
        });
    });
});
