export { default as Slider } from './slider.vue';
export { default as RangeSlider } from './range-slider.vue';
export {
    rangeSliderParts,
    sliderColors,
    sliderOrientations,
    sliderParts,
    sliderSizes,
} from './types';
export type {
    RangeSliderAriaValueText,
    RangeSliderEndpointValueText,
    RangeSliderInputAttrs,
    RangeSliderPart,
    RangeSliderProps,
    RangeSliderThumb,
    RangeSliderThumbOptions,
    RangeSliderTrackSlotProps,
    RangeSliderTooltip,
    RangeSliderTooltipOptions,
    RangeSliderValue,
    RangeSliderValidationMessage,
    SliderColor,
    SliderInputAttrs,
    SliderMark,
    SliderMarkColor,
    SliderMarkInput,
    SliderOrientation,
    SliderPart,
    SliderProps,
    SliderPresetColor,
    SliderSize,
    SliderThumb,
    SliderThumbMode,
    SliderThumbOptions,
    SliderTrackSlotProps,
    SliderTooltip,
    SliderTooltipAnchor,
    SliderTooltipMode,
    SliderTooltipOptions,
    SliderTooltipSlotProps,
    SliderValueFormatter,
} from './types';
